#!/usr/bin/env python

import math

# import of relevant libraries.
import rospy # module for ROS APIs
import tf

# import msg/action/srv
from geometry_msgs.msg import Twist # message type for cmd_vel
from nav_msgs.msg import Odometry # message type for odom

from ppgapt.msg import Registration_msg
from ppgapt.msg import Kill_msg
from ppgapt.msg import Alive_msg
from ppgapt.msg import New_gen_msg
from ppgapt.msg import Ready_msg
from ppgapt.msg import Hunt_msg


# Constants.
DEFAULT_PREDATOR_LINEAR_VELOCITY = 10 # m/s
CUSTOM_KILL_TOPIC = '/kill'
DEFAULT_ODOM_TOPIC = 'odom'
DEFAULT_CMD_VEL_TOPIC = "cmd_vel"
DEFAULT_REGISTRATION_TOPIC = "/registration"
DEFAULT_ALIVE_TOPIC = '/alive'
DEFAULT_NEW_GENERATION_TOPIC = '/new_gen'
DEFAULT_READY_TOPIC = '/ready'
DEFAULT_HUNT_TOPIC = '/hunt'

LASER_ANGLE_FRONT = 0 # radians
MIN_THRESHOLD_DISTANCE = 0.5 # m, threshold distance.
KILLED_THRESHOLD = 0.75

NUM_PREY = 3 # Number of prey robots
FREQUENCY = 10
MAX_DIST = 1000

class Predator():
    def __init__(self):
        """Constructor."""
        self.namespace = rospy.get_namespace()

        self.alives = set()
        self.odom_dict = {}

        self.preys = {}
        self.hunting = True

        # pub/subs
        self._cmd_pub = rospy.Publisher(self.namespace + DEFAULT_CMD_VEL_TOPIC, Twist, queue_size=1)
        self._kill_pub = rospy.Publisher(CUSTOM_KILL_TOPIC, Kill_msg, queue_size=1)
        self._odom_pub_ = rospy.Publisher(self.namespace + DEFAULT_ODOM_TOPIC, Odometry, queue_size=1)
        self._ready_pub_ = rospy.Publisher(DEFAULT_READY_TOPIC, Ready_msg, queue_size=1)

        # create service for registration
        self._registration_sub = rospy.Subscriber(DEFAULT_REGISTRATION_TOPIC, Registration_msg, self.registration_callback)

        self._odom_sub = rospy.Subscriber(self.namespace + DEFAULT_ODOM_TOPIC, Odometry, self.odom_callback)
        self._is_alive_sub = rospy.Subscriber(DEFAULT_ALIVE_TOPIC, Alive_msg, self._is_alive_callback, queue_size=1)
        self._new_gen_sub = rospy.Subscriber(DEFAULT_NEW_GENERATION_TOPIC, New_gen_msg, self._new_gen_callback, queue_size=1)
        self._hunt_sub = rospy.Subscriber(DEFAULT_HUNT_TOPIC, Hunt_msg, self._hunt_callback, queue_size=1)

        # vel values
        self.linear_velocity = 2 # m/s
        self.angular_velocity = math.pi/4 # rad/s

        self.x, self.y, self.theta = None, None, None

        self.start_x, self.start_y =rospy.get_param(self.namespace[:-1] + "_x"), rospy.get_param(self.namespace[:-1] + "_y")

    def registration_callback(self, msg):
        if msg.robotname.data not in self.preys:
            self.preys[msg.robotname.data] = (None,None)

        rospy.Subscriber(msg.robotname.data + DEFAULT_ODOM_TOPIC, Odometry, self.location_callback, (msg.robotname.data))

    def _hunt_callback(self, msg):
        self.hunting = True

    def location_callback(self, msg, args):
        self.preys[args] = (msg.pose.pose.position.x, msg.pose.pose.position.y)

    def odom_callback(self, msg):
        self.x, self.y, self.theta = msg.pose.pose.position.x, msg.pose.pose.position.y, tf.transformations.euler_from_quaternion([msg.pose.pose.orientation.x, msg.pose.pose.orientation.y, msg.pose.pose.orientation.z, msg.pose.pose.orientation.w])[2]

    def _laser_callback(self, msg):
        i = int((LASER_ANGLE_FRONT - msg.angle_min) / msg.angle_increment)
        if msg.ranges[i] <= MIN_THRESHOLD_DISTANCE:
            self._close_obstacle = True
        else:
            self._close_obstacle = False

    def find_target_prey(self):
        while not self.alives:
            continue

        min_dist = MAX_DIST
        target = None
        for prey in self.alives:

            if prey not in self.preys or self.preys[prey][0] == None:
                continue

            dist_to_prey = math.sqrt((self.x - self.preys[prey][0])**2 + (self.y - self.preys[prey][1])**2)
            if dist_to_prey < min_dist:
                min_dist = dist_to_prey
                target = prey

        return target 

    def run(self):

        while True:

            if not self.hunting or (len(self.preys) != NUM_PREY):
                continue
            
            target = self.find_target_prey()

            if not target:
                continue

            target_x, target_y = self.preys[target]

            if math.sqrt((self.x - target_x)**2 + (self.y - target_y)**2) < KILLED_THRESHOLD:
                # self.kill_prey(target)
                # Move away from killed bot

                self.kill_prey(target)
                self.rotate_in_place(math.pi)
                self.move_forward(1)
                rospy.sleep(.2)
            
            else:
                tan_angle = math.atan2(target_y - self.y, target_x - self.x)

                angle = tan_angle - self.theta

                twist_msg = Twist()
                twist_msg.angular.z = angle
                twist_msg.linear.x = DEFAULT_PREDATOR_LINEAR_VELOCITY
                self._cmd_pub.publish(twist_msg)

    def kill_prey(self, target):

        kill_msg = Kill_msg()
        kill_msg.robot_name = target
        self._kill_pub.publish(kill_msg)
        self.alives.remove(kill_msg.robot_name)


    def _is_alive_callback(self, msg):
        self.alives.add(msg.robot_name)

    def _new_gen_callback(self, msg):
        # calls back all robot's to their initial pos
        self.hunting = False
        rospy.sleep(2)
        rot = math.atan2(self.start_y - self.y, self.start_x - self.x) - self.theta
        while rot < 0:
            rot += (2*math.pi)
        while rot > (2*math.pi):
            rot -= (2*math.pi)

        dist = math.sqrt((self.x - self.start_x)**2 + (self.y - self.start_y)**2)
        # print(self.x, self.y, self.theta)
        # print(rot, dist, (2*math.pi)-self.theta)
        self.linear_velocity = 1
        self.angular_velocity = math.pi / 4
        # print("pre rotation: ", self.theta)
        self.rotate_in_place(rot)
        rospy.sleep(2)
        # print("post rotation: ", self.theta)
        self.move_forward(dist)
        self.rotate_in_place((2*math.pi)-self.theta)
        
        # print("now at", self.x, self.y, self.theta)
        self.linear_velocity = 0
        self.angular_velocity = 0

        ready_msg = Ready_msg()
        ready_msg.ready = True

        self._ready_pub_.publish(ready_msg)
        

    def move_forward(self, distance):

        # Rate at which to operate the while loop.
        rate = rospy.Rate(FREQUENCY)

        # Setting velocities. 
        twist_msg = Twist()
        twist_msg.linear.x = self.linear_velocity
        start_time = rospy.get_rostime()
        if self.linear_velocity != 0:
            duration = rospy.Duration(distance/twist_msg.linear.x)
        else:
            duration = rospy.Duration(0)

        # Loop.
        while not rospy.is_shutdown():
            # Check if traveled of given distance based on time.
            if rospy.get_rostime() - start_time >= duration:
                break

            # Publish message.
            # if self._close_obstacle:
            #     self.stop()
            # else:
            self._cmd_pub.publish(twist_msg)

            # Sleep to keep the set publishing frequency.
            rate.sleep()

        # Traveled the required distance, stop.
        self.stop()
        
    def rotate_in_place(self, rotation_angle):

        twist_msg = Twist()
        twist_msg.angular.z = self.angular_velocity
        
        if self.linear_velocity != 0:
            duration = rotation_angle / twist_msg.angular.z
        else:
            duration = 0
        start_time = rospy.get_rostime()
        rate = rospy.Rate(FREQUENCY)
        while not rospy.is_shutdown():
            # Check if done
            if rospy.get_rostime() - start_time >= rospy.Duration(duration):
                break
                
            # Publish message.
            self._cmd_pub.publish(twist_msg)
            
            # Sleep to keep the set frequency.
            rate.sleep()

        # Rotated the required angle, stop.
        self.stop()

    def stop(self):

        twist_msg = Twist()
        self._cmd_pub.publish(twist_msg)


def main():
    """Main function."""

    # 1st. initialization of node.s
    rospy.init_node('predator')

    # Sleep for a few seconds to wait for the registration.
    rospy.sleep(2)

    # Initialization of the class for the Leader.
    predator = Predator()
    rospy.sleep(2)
    
    predator.run()


if __name__ == "__main__":
    """Run the main function."""
    main()
